
const Data =[
  
  {
    name: "Pups in the Park",
    url_name: "pups‑in‑the‑park",
    desc: "A fun, family and dog‑friendly community event with activities and socializing for pups.",
    type: "Event",
    isHighlight: false,
    location: "1490 S Broad Street, Winston-Salem, NC 27101",
    date: "March 7, 2026",
    zip: "27101",
    month: "March",
    parking: true,
    wheelchair: true,
    website: "https://www.cityofws.org/2078/Events",
    day: 7,
    time: "11 AM - 2 PM",
    contact: "336-727-8000"
  },
  {
    name: "Pot of Gold Coin Hunt",
    url_name: "pot‑of‑gold‑coin‑hunt",
    desc: "Community scavenger hunt with prizes hidden around Winston‑Salem parks celebrating St. Patrick’s season.",
    type: "Event",
    isHighlight: false,
    location: "400 Leisure Lane, Winston Salem, NC 27013",
    date: "March 14, 2026",
    zip: "27103",
    month: "March",
    parking: true,
    wheelchair: true,
    website: "https://www.cityofws.org/2078/Events",
    day: 14,
    time: "10 AM - 12 PM",
    contact: "336 727 8000"
  },
  {
    name: "UNCSA Improvised Music and Jazz Festival",
    url_name: "uncsa‑improvised‑music‑and‑jazz‑festival",
    desc: "Musical festival showcasing jazz and improvised music performances by UNCSA students and guest artists.",
    type: "Event",
    isHighlight: false,
    location: "Downtown Winston‑Salem, Winston‑Salem, NC",
    date: "March 27, 2026",
    zip: "27101",
    month: "March",
    parking: true,
    wheelchair: true,
    website: "https://www.uncsa.edu/performances/Events/20260327-jazzfest.aspx",
    day: 27,
    time: "1:00 PM",
    contact: "336-721-1945"
  },
  {
    name: "Forsyth County Central Library",
    url_name: "forsyth-central-library",
    desc: "Public library offering free Educational Resources, books, and computer access for all ages.",
    type: "Educational",
    isHighlight: true,
    location: "660 W 5th St, Winston‑Salem, NC, 27101",
    date: "Ongoing",
    zip: "27101",
    month: "",
    parking: true,
    wheelchair: true,
    website: "https://www.forsyth.cc/library/",
    day: "",
    time: "Varies",
    contact: "336-703-2665"
  },
  {
    name: "Face to Face with Cynthia Erivo",
    url_name: "face‑to‑face‑cynthia‑erivo",
    desc: "Cynthia Erivo will share insights on her career as an actress.",
    type: "Event",
    isHighlight: true,
    location: "Lawrence Joel Veterans Memorial Coliseum, Winston‑Salem, NC",
    date: "April 15, 2026",
    zip: "27105",
    month: "April",
    parking: true,
    wheelchair: true,
    website: "https://facetoface.wfu.edu/cynthia-erivo/",
    day: 15,
    time: "7:30 PM",
    contact: "(336) 758‑6615"
  },
      {
    name: "The Resource Winston-Salem",
    url_name: "the-Resource-winston-salem",
    desc: "Employment support and career development services.",
    type: "Resource",
    isHighlight: false,
    location: "1292 S Stratford Rd, Winston-Salem, NC 27103",
    date: "Ongoing",
    zip: "27103",
    month: "",
    parking: true,
    wheelchair: true,
    website: "http://www.theResource.com/",
    day: "",
    time: "8 AM - 12:30 PM, 1:30 - 5 PM, Monday - Friday",
    contact: "336-896-1000"
  },

  {
    name: "Second Harvest Food Bank NWNC",
    url_name: "second-harvest-food-bank-nwnc",
    desc: "Volunteers at this food bank support the community by sorting, packing, and organizing food, working in partnership with local agencies to help those in need.",
    type: "Volunteering",
    isHighlight: true,
    location: "3330 Shorefair Dr, Winston-Salem, NC 27105",
    date: "Ongoing",
    zip: "27105",
    month: "",
    parking: true,
    wheelchair: true,
    website: "https://www.secondharvestnwnc.org/",
    day: "",
    time: "Shift time varies",
    contact: "336-784-5770"
  },
  {
    name: "Novant Health Hospital Volunteer",
    url_name: "hospital-volunteer",
    desc: "Assist with patient support, visitor guidance, and restocking of materials.",
    type: "Volunteering",
    isHighlight: false,
    location: "3333 Silas Creek Pkwy, Winston-Salem, NC 27103",
    date: "Ongoing",
    zip: "27103",
    month: "",
    parking: true,
    wheelchair: true,
    website: "https://www.samaritanforsyth.org/",
    day: "",
    time: "Shift time varies",
    contact: ""
  },
  {
    name: "City with Dwellings",
    url_name: "city-with-dwellings",
    desc: "Community center aiding people experiencing homelessness. City with Dwellings provides hygiene kits, financial assistance, and access to a mailing address.",
    type: "Resource",
    isHighlight: false,
    location: "502 N Broad St, Winston-Salem, NC 27101",
    date: "Ongoing",
    zip: "27101",
    month: "",
    parking: true,
    wheelchair: true,
    website: "https://www.citywithdwellings.org/",
    day: "",
    time: "2-4 PM, Monday - Wednesday",
    contact: "336-790-9766"
  },
  {
    name: "iCan House",
    url_name: "ican-house",
    desc: "Provides support for neurodivergent people. Teaches social and life skills with a fun and interactive curriculum.",
    type: "Educational",
    isHighlight: false,
    location: "952 W 4th St Suite 205, Winston-Salem, NC 27101",
    date: "Ongoing",
    zip: "27101",
    month: "",
    parking: true,
    wheelchair: true,
    website: "https://icanhouse.org/",
    day: "",
    time: "Varies",
    contact: "336-723-0050"
  },
  {
    name: "The Winston-Salem Foundation",
    url_name: "the-winston-salem-foundation",
    desc: "Nonprofit encouraging charitable giving and providing scholarships and grants to local nonprofits.",
    type: "Resource",
    isHighlight: false,
    location: "751 W 4th St #200, Winston-Salem, NC 27101",
    date: "Ongoing",
    zip: "27101",
    month: "",
    parking: true,
    wheelchair: true,
    website: "http://www.wsfoundation.org/",
    day: "",
    time: "Monday to Friday, 8:30 AM - 5:00 PM",
    contact: "336-725-2382"
  },
  {
    name: "Center For Creative Economy",
    url_name: "center-for-creative-economy",
    desc: "Non-profit supporting entrepreneurs in building successful businesses. This includes a 6-week boot camp teaching entrepreneurs to develop ideas and find potential customers.",
    type: "Educational",
    isHighlight: false,
    location: "500 W 5th St, Winston-Salem, NC 27101",
    date: "Ongoing",
    zip: "27101",
    month: "",
    parking: true,
    wheelchair: true,
    website: "https://ccetriad.com/",
    day: "",
    time: "9 AM - 5 PM, Monday-Friday",
    contact: "336-462-9429"
  },
  {
    name: "greenest",
    url_name: "greenest-winston-salem",
    desc: "Nonprofit providing pre-owned furniture to Winston-Salem residents for a small fee.",
    type: "Resource",
    isHighlight: false,
    location: "630 Brookstown Ave, Winston-Salem, NC 27101",
    date: "Ongoing",
    zip: "27101",
    month: "",
    parking: true,
    wheelchair: true,
    website: "http://www.greenestws.com/",
    day: "",
    time: "10 AM - 4 PM, Tuesday-Friday",
    contact: "336-661-8091"
  },
  {
    name: "Crossnore Communities for Children ",
    url_name: "crossnore-communities-for-children-ws",
    desc: "Nonprofit assisting with foster care and adoption for children. Crossnore Communities for Children also offers therapy services.",
    type: "Resource",
    isHighlight: false,
    location: "1001 Reynolda Rd NW, Winston-Salem, NC 27104",
    date: "Ongoing",
    zip: "27104",
    month: "",
    parking: true,
    wheelchair: true,
    website: "http://crossnore.org/",
    day: "",
    time: "8:30 AM - 5 PM, Monday - Friday",
    contact: "336-721-7600"
  },
  
  {
    name: "Forsyth County Department of Social Services",
    url_name: "forsyth-county-department-social-services",
    desc: "Provides child support and adoption services. Also assists with employment and financial support.",
    type: "Resource",
    isHighlight: false,
    location: "741 Highland Ave, Winston-Salem, NC 27101",
    date: "Ongoing",
    zip: "27101",
    month: "",
    parking: true,
    wheelchair: true,
    website: "https://www.ncdhhs.gov/divisions/social-services/forsyth-county-department-social-services",
    day: "",
    time: "8AM - 5PM, Monday - Friday",
    contact: "336-703-3800"
  },
  {
    name: "Crisis Control Ministry",
    url_name: "crisis-control-ministry",
    desc: "Provides emergency assistance for food, utilities, and medication.",
    type: "Resource",
    isHighlight: false,
    location: "200 10th St E, Winston-Salem, NC 27101",
    date: "Ongoing",
    zip: "27101",
    month: "",
    parking: true,
    wheelchair: true,
    website: "http://www.crisiscontrol.org",
    day: "",
    time: "9 AM - 12 PM & 1-4 PM, Monday - Friday",
    contact: "336-724-7453"
  },
  {
    name: "3RC EnviroStation",
    url_name: "Resource-recovery-reduction",
    desc: "Free Electronic waste and Household Hazardous Waste disposal services for residents.",
    type: "Resource",
    isHighlight: false,
    location: "1401 S Martin Luther King Jr Dr, Winston-Salem, NC 27107",
    date: "Ongoing",
    zip: "27107",
    month: "",
    parking: true,
    wheelchair: false,
    website: "https://www.cityofws.org/1158/3RC-EnviroStation---Household-Hazardous-",
    day: "",
    time: "9 AM - 3 PM, Wednesday-Saturday",
    contact: "336-784-4300"
  },


]

export default Data;




// const Data =[
//      {
//     name: "Hospital Volunteer",
//     url_name: 'hospital-volunteer',
//     desc: "Assist nurses and staff with patient support, visitor guidance, and administrative tasks at the local hospital.",
//     type: "Volunteering",
//     location: "Downtown Community Hospital",
//     date: "Ongoing",
//        zip: "12345",
//        parking: true,
//        wheelchair:false,
//       isHighlight:false,
//      website: 'hospitalVolunteering.com',
     
//       time: 'All day',
//     contact: "volunteer@dch.org"
//   },
//   {
//     name: "Community Food Bank",
//       url_name: 'community-food-bank',
//     desc: "Free groceries available weekly for individuals and families in need. Volunteers also welcome to help with sorting and distribution.",
//     type: "Resource",
//     location: "Sunset Avenue Food Pantry",
//     date: "Every Saturday, 10 AM – 2 PM",
//     month: "Oct",
//       parking: true,
//        wheelchair:true,
//      isHighlight:false,
//       day: '8',
//       website: 'communityfoodbank.org',
//       time: '10 AM - 2 PM',
//     contact: "info@sunsetpantry.org",
//     zip: "23456"
//   },
//   {
//     name: "Neighborhood Cleanup Day",
//       url_name: 'neighborhood-cleanup',
//     desc: "Join your neighbors for a park and street cleanup to improve our community spaces. Supplies provided.",
//     type: "Event",
//      isHighlight:true,
//     location: "Riverside Park",
//     date: "Oct 12, 2025, 9 AM – 12 PM",
//     website: 'cleanup.org',
//       zip: "34567",
//         parking: false,
//        wheelchair:false,
//          month: "Oct",
//       day: '10',
//       time: '8 PM',
//     contact: "Events@greenteam.org"
//   },
//   {
//     name: "Coding for Youth Workshop",
//       url_name: 'youth-coding',
//     desc: "Free beginner-friendly coding sessions for middle and high school students. Learn the basics of web and app development.",
//     type: "Educational",
//     location: "Community Tech Center",
//      isHighlight:true,
//     website: 'youthcoders.edu',
//       parking: true,
//        wheelchair:true,
//     date: "Oct 18, 2025, 4 PM – 6 PM",
//      month: "Oct",
//       day: '16',
//       time: '1-4PM',
//      zip: "45678",
     
//     contact: "learn@ctc.org"
//   },
//   {
//     name: "Winter Clothing Drive",
//       url_name: 'clothing-drive',
//     desc: "Donate or pick up warm clothing items for the upcoming winter season. Coats, hats, and gloves appreciated.",
//     type: "Resource",
//      isHighlight:false,
//     location: "Main Street Community Hall",
//     date: "Nov 1 – Nov 30, 2025",
//      zip: "56789",
//           month: "Oct",
//             parking: false,
//        wheelchair:true,
//           website: 'clothingdrive.org',
//       day: '23',
//       time: 'All day',
//     contact: "clothing@msch.org"
//   },
//   {
//   name: "Free Legal Aid Clinic",
//     url_name: 'legal-aid-clinic',
//   desc: "Get guidance on civil, family, and tenant-related legal issues from volunteer attorneys. Walk-ins welcome, no prior appointment needed.",
//   type: "Resource",
//    isHighlight: true,
//   location: "Downtown Legal Center",
//   website: 'legalaid.org',
//      month: "Nov",
//       day: '2',
//         parking: true,
//        wheelchair:true,
//       time: '10AM-3PM',
//   date: "Every Wednesday, 1 PM – 5 PM",
//   zip: "67890",
//   contact: "help@dlegal.org"
// }

// ]

// export default Data;